import { transports } from 'remixjs/project';


Component({
  options: { addGlobalClass: true },

  properties: {
    onCancel: String,
		onError: String,
		onChange: String,
		onColumnChange: String,
		onTouchStart: String,
		onTouchMove: String,
		onTouchCancel: String,
		onTouchEnd: String,
		onTap: String,
		onLongPress: String,
		onLongTap: String,
		onTransitionEnd: String,
		onAnimationStart: String,
		onAnimationIteration: String,
		onAnimationEnd: String,
		onTouchForceChange: String,
		child: Object,
		innerText: String,
		uuid: String,
		styles: String,
		className: String,
		mode: String,
		disabled: Boolean,
		range: Object,
		rangeKey: String,
		value: Number,
		start: String,
		end: String,
		fields: String,
		customItem: String,
		
  },

  data: {
    onCancel: null,
		onError: null,
		onChange: null,
		onColumnChange: null,
		onTouchStart: null,
		onTouchMove: null,
		onTouchCancel: null,
		onTouchEnd: null,
		onTap: null,
		onLongPress: null,
		onLongTap: null,
		onTransitionEnd: null,
		onAnimationStart: null,
		onAnimationIteration: null,
		onAnimationEnd: null,
		onTouchForceChange: null,
		child: null,
		innerText: null,
		uuid: null,
		styles: null,
		className: null,
		mode: 'selector',
		disabled: false,
		range: [],
		rangeKey: null,
		value: 0,
		start: null,
		end: null,
		fields: 'day',
		customItem: null,
		
  },

  methods: {
    onCancel (e) { transports.view.dispatch('onCancel', this.data.uuid, e); },
		onError (e) { transports.view.dispatch('onError', this.data.uuid, e); },
		onChange (e) { transports.view.dispatch('onChange', this.data.uuid, e); },
		onColumnChange (e) { transports.view.dispatch('onColumnChange', this.data.uuid, e); },
		onTouchStart (e) { transports.view.dispatch('onTouchStart', this.data.uuid, e); },
		onTouchMove (e) { transports.view.dispatch('onTouchMove', this.data.uuid, e); },
		onTouchCancel (e) { transports.view.dispatch('onTouchCancel', this.data.uuid, e); },
		onTouchEnd (e) { transports.view.dispatch('onTouchEnd', this.data.uuid, e); },
		onTap (e) { transports.view.dispatch('onTap', this.data.uuid, e); },
		onLongPress (e) { transports.view.dispatch('onLongPress', this.data.uuid, e); },
		onLongTap (e) { transports.view.dispatch('onLongTap', this.data.uuid, e); },
		onTransitionEnd (e) { transports.view.dispatch('onTransitionEnd', this.data.uuid, e); },
		onAnimationStart (e) { transports.view.dispatch('onAnimationStart', this.data.uuid, e); },
		onAnimationIteration (e) { transports.view.dispatch('onAnimationIteration', this.data.uuid, e); },
		onAnimationEnd (e) { transports.view.dispatch('onAnimationEnd', this.data.uuid, e); },
		onTouchForceChange (e) { transports.view.dispatch('onTouchForceChange', this.data.uuid, e); }
  },

  lifetimes: {
    created () { transports.view.dispatch('created', this.data.uuid); },
    attached () { transports.view.dispatch('attached', this.data.uuid); },
    detached () { transports.view.dispatch('detached', this.data.uuid); },
    ready () { transports.view.dispatch('ready', this.data.uuid); },
    moved () { transports.view.dispatch('moved', this.data.uuid); },
    error (error) { transports.view.dispatch('detached', this.data.uuid, error); }
  },
});
