export default {
  vid: null,
	parent: null,
	style: null,
	className: null,
	id: null,
	src: null,
	loop: false,
	controls: true,
	poster: null,
	name: null,
	author: null,
	onTouchStart: null,
	onTouchMove: null,
	onTouchCancel: null,
	onTouchEnd: null,
	onTap: null,
	onLongPress: null,
	onLongTap: null,
	onTouchForceChange: null,
	onTransitionEnd: null,
	onAnimationStart: null,
	onAnimationIteration: null,
	onAnimationEnd: null,
	onError: null,
	onPlay: null,
	onPause: null,
	onTimeUpdate: null,
	onEnded: null
}

