import { transports } from 'remixjs/project';


Component({
  options: { addGlobalClass: true },

  properties: {
    onTouchStart: String,
		onTouchMove: String,
		onTouchCancel: String,
		onTouchEnd: String,
		onTap: String,
		onLongPress: String,
		onLongTap: String,
		onTouchForceChange: String,
		onTransitionEnd: String,
		onAnimationStart: String,
		onAnimationIteration: String,
		onAnimationEnd: String,
		onMarkerTap: String,
		onLabelTap: String,
		onControlTap: String,
		onCalloutTap: String,
		onUpdated: String,
		onRegionChange: String,
		onPoiTap: String,
		uuid: String,
		style: String,
		className: String,
		longitude: Number,
		latitude: Number,
		scale: Number,
		markers: Array,
		covers: Array,
		polyline: Array,
		circles: Array,
		controls: Array,
		includePoints: Array,
		showLocation: Boolean,
		polygons: Array,
		subkey: String,
		layerStyle: Number,
		rotate: Number,
		skew: Number,
		enable3D: Boolean,
		showCompass: Boolean,
		showScale: Boolean,
		enableOverlooking: Boolean,
		enableZoom: Boolean,
		enableScroll: Boolean,
		enableRotate: Boolean,
		enableSatellite: Boolean,
		enableTraffic: Boolean,
		setting: Object,
		
  },

  data: {
    onTouchStart: null,
		onTouchMove: null,
		onTouchCancel: null,
		onTouchEnd: null,
		onTap: null,
		onLongPress: null,
		onLongTap: null,
		onTouchForceChange: null,
		onTransitionEnd: null,
		onAnimationStart: null,
		onAnimationIteration: null,
		onAnimationEnd: null,
		onMarkerTap: null,
		onLabelTap: null,
		onControlTap: null,
		onCalloutTap: null,
		onUpdated: null,
		onRegionChange: null,
		onPoiTap: null,
		uuid: null,
		style: null,
		className: null,
		longitude: null,
		latitude: null,
		scale: 16,
		markers: null,
		covers: null,
		polyline: null,
		circles: null,
		controls: null,
		includePoints: null,
		showLocation: false,
		polygons: null,
		subkey: null,
		layerStyle: 1,
		rotate: 0,
		skew: 0,
		enable3D: false,
		showCompass: false,
		showScale: false,
		enableOverlooking: false,
		enableZoom: false,
		enableScroll: false,
		enableRotate: false,
		enableSatellite: false,
		enableTraffic: false,
		setting: null,
		
  },

  methods: {
    onTouchStart (e) { transports.view.dispatch('onTouchStart', this.data.uuid, e); },
		onTouchMove (e) { transports.view.dispatch('onTouchMove', this.data.uuid, e); },
		onTouchCancel (e) { transports.view.dispatch('onTouchCancel', this.data.uuid, e); },
		onTouchEnd (e) { transports.view.dispatch('onTouchEnd', this.data.uuid, e); },
		onTap (e) { transports.view.dispatch('onTap', this.data.uuid, e); },
		onLongPress (e) { transports.view.dispatch('onLongPress', this.data.uuid, e); },
		onLongTap (e) { transports.view.dispatch('onLongTap', this.data.uuid, e); },
		onTouchForceChange (e) { transports.view.dispatch('onTouchForceChange', this.data.uuid, e); },
		onTransitionEnd (e) { transports.view.dispatch('onTransitionEnd', this.data.uuid, e); },
		onAnimationStart (e) { transports.view.dispatch('onAnimationStart', this.data.uuid, e); },
		onAnimationIteration (e) { transports.view.dispatch('onAnimationIteration', this.data.uuid, e); },
		onAnimationEnd (e) { transports.view.dispatch('onAnimationEnd', this.data.uuid, e); },
		onMarkerTap (e) { transports.view.dispatch('onMarkerTap', this.data.uuid, e); },
		onLabelTap (e) { transports.view.dispatch('onLabelTap', this.data.uuid, e); },
		onControlTap (e) { transports.view.dispatch('onControlTap', this.data.uuid, e); },
		onCalloutTap (e) { transports.view.dispatch('onCalloutTap', this.data.uuid, e); },
		onUpdated (e) { transports.view.dispatch('onUpdated', this.data.uuid, e); },
		onRegionChange (e) { transports.view.dispatch('onRegionChange', this.data.uuid, e); },
		onPoiTap (e) { transports.view.dispatch('onPoiTap', this.data.uuid, e); }
  },

  lifetimes: {
    created () { transports.view.callLifecycle('created', this.data.uuid); },
    attached () { transports.view.callLifecycle('attached', this.data.uuid); },
    detached () { transports.view.callLifecycle('detached', this.data.uuid); },
    ready () { transports.view.callLifecycle('ready', this.data.uuid); },
    moved () { transports.view.callLifecycle('moved', this.data.uuid); },
    error (error) { transports.view.callLifecycle('detached', this.data.uuid, error); }
  },
});
