export default {
  child: null,
	silbing: null,
	innerText: null,
	vid: null,
	parent: null,
	style: null,
	className: null,
	indicatorDots: false,
	indicatorColor: 'rgba(0, 0, 0, .3)',
	indicatorActiveColor: '#000000',
	autoplay: false,
	current: 0,
	interval: 5000,
	duration: 500,
	circular: false,
	vertical: false,
	previousMargin: '0px',
	nextMargin: '0px',
	displayMultipleItems: 1,
	skipHiddenItemLayou: false,
	easingFunction: 'default',
	onTouchStart: null,
	onTouchMove: null,
	onTouchCancel: null,
	onTouchEnd: null,
	onTap: null,
	onLongPress: null,
	onLongTap: null,
	onTouchForceChange: null,
	onTransitionEnd: null,
	onAnimationStart: null,
	onAnimationIteration: null,
	onAnimationEnd: null,
	onChange: null,
	onAnimationFinish: null
}

