export default {
  vid: null,
	parent: null,
	style: null,
	className: null,
	min: 0,
	max: 100,
	step: 1,
	disabled: false,
	value: 0,
	color: '#e9e9e9',
	selectedColor: '#1aad19',
	backgroundColor: '#e9e9e9',
	activeColor: '#1aad19',
	blockSize: 28,
	blockColor: '#ffffff',
	showValue: false,
	onTouchStart: null,
	onTouchMove: null,
	onTouchCancel: null,
	onTouchEnd: null,
	onTap: null,
	onLongPress: null,
	onLongTap: null,
	onTouchForceChange: null,
	onTransitionEnd: null,
	onAnimationStart: null,
	onAnimationIteration: null,
	onAnimationEnd: null,
	onChange: null,
	onChanging: null
}

