export default {
  child: null,
	silbing: null,
	innerText: null,
	vid: null,
	parent: null,
	style: null,
	className: null,
	mode: 'selector',
	disabled: false,
	range: [],
	rangeKey: null,
	value: 0,
	start: null,
	end: null,
	fields: 'day',
	customItem: null,
	onTouchStart: null,
	onTouchMove: null,
	onTouchCancel: null,
	onTouchEnd: null,
	onTap: null,
	onLongPress: null,
	onLongTap: null,
	onTouchForceChange: null,
	onTransitionEnd: null,
	onAnimationStart: null,
	onAnimationIteration: null,
	onAnimationEnd: null,
	onCancel: null,
	onError: null,
	onChange: null,
	onColumnChange: null
}

