export default {
  vid: null,
	parent: null,
	style: null,
	className: null,
	readOnly: false,
	placeholder: null,
	showImgSize: false,
	showImgToolbar: false,
	showImgResize: false,
	onTouchStart: null,
	onTouchMove: null,
	onTouchCancel: null,
	onTouchEnd: null,
	onTap: null,
	onLongPress: null,
	onLongTap: null,
	onTouchForceChange: null,
	onTransitionEnd: null,
	onAnimationStart: null,
	onAnimationIteration: null,
	onAnimationEnd: null,
	onFocus: null,
	onBlur: null,
	onInput: null,
	onReady: null,
	onStatusChange: null
}

