export default {
  vid: null,
	parent: null,
	style: null,
	className: null,
	src: null,
	mode: 'scaleToFill',
	webp: false,
	lazyLoad: false,
	showMenuByLongpress: false,
	onTouchStart: null,
	onTouchMove: null,
	onTouchCancel: null,
	onTouchEnd: null,
	onTap: null,
	onLongPress: null,
	onLongTap: null,
	onTouchForceChange: null,
	onTransitionEnd: null,
	onAnimationStart: null,
	onAnimationIteration: null,
	onAnimationEnd: null,
	onLoad: null,
	onError: null
}

