export default {
  child: null,
	silbing: null,
	innerText: null,
	vid: null,
	parent: null,
	style: null,
	className: null,
	scrollX: false,
	scrollY: false,
	upperThreshold: 50,
	lowerThreshold: 50,
	scrollTop: null,
	scrollLeft: null,
	scrollIntoView: null,
	scrollWithAnimation: false,
	enableBackToTop: false,
	enableFlex: false,
	scrollAnchoring: false,
	onTouchStart: null,
	onTouchMove: null,
	onTouchCancel: null,
	onTouchEnd: null,
	onTap: null,
	onLongPress: null,
	onLongTap: null,
	onTouchForceChange: null,
	onTransitionEnd: null,
	onAnimationStart: null,
	onAnimationIteration: null,
	onAnimationEnd: null,
	onScrollToUpper: null,
	onScrollToLower: null,
	onScroll: null
}

